set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 4.5000 -nets VDD -layer metal7 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 215.7000 -nets VDD -layer metal7 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 215.5700 -nets VDD -layer metal8 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 4.5000 -nets VDD -layer metal8 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 4.5000 -nets VDD -layer metal9 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 215.7000 -nets VDD -layer metal9 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 215.5700 -nets VDD -layer metal10 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 4.5000 -nets VDD -layer metal10 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 11.5000 -nets VSS -layer metal7 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 208.7000 -nets VSS -layer metal7 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 208.5700 -nets VSS -layer metal8 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 11.5000 -nets VSS -layer metal8 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 11.5000 -nets VSS -layer metal9 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 208.7000 -nets VSS -layer metal9 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 208.5700 -nets VSS -layer metal10 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 11.5000 -nets VSS -layer metal10 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 29.8700 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.2300 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.5900 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.9500 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.3100 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.6700 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 134.0300 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 151.3900 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 168.7500 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 186.1100 -nets VDD  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 34.0000 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 51.3600 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 68.7200 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.0800 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 103.4400 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.8000 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 138.1600 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 155.5200 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 172.8800 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.2400 -nets VSS  -layer metal6 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 29.6050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 47.2050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 64.8050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.6050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.2050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 116.8050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 134.4050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 151.2050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 168.8050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 186.4050 -nets VDD  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 33.7350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 51.3350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.9350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 85.7350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 103.3350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 120.9350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 138.5350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 155.3350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 172.9350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 190.5350 -nets VSS  -layer metal7 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 29.5950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.1950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.7950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.5950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.1950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.7950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 133.5950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 151.1950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 168.7950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 186.3950 -nets VDD  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 33.7950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 51.3950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 68.9950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.7950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 103.3950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.9950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 137.7950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 155.3950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 172.9950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.5950 -nets VSS  -layer metal8 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 30.3700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.3700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 63.9700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.5700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.1700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 116.7700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 134.3700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 151.9700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 169.5700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 185.5700 -nets VDD  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 34.5700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.5700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.1700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 85.7700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 103.3700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 120.9700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 138.5700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 156.1700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 173.7700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 189.7700 -nets VSS  -layer metal9 -width 2.5000 -pitch_within_group 17.380 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.0700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VDD
create_power_straps  -direction vertical  -start_at 30.4950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.4950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.0950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.6950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.2950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.8950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 134.4950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 152.0950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 168.0950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 185.6950 -nets VDD  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 2.0000 -start_high_ends coordinate  -start_high_ends_coordinate 218.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VSS
create_power_straps  -direction vertical  -start_at 34.4950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.4950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 68.0950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.6950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 103.2950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.8950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 138.4950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 156.0950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 172.0950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 189.6950 -nets VSS  -layer metal10 -width 2.5000 -pitch_within_group 17.370 -start_low_ends coordinate  -start_low_ends_coordinate 9.0000 -start_high_ends coordinate  -start_high_ends_coordinate 211.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
